name: dockerflow

on:
  push:
    branches: [feature/dockerizar]
  workflow_dispatch:



jobs:
  docker-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: matope1 # ${{ secrets.DOCKER_USERNAME }}
      DOCKER_HUB_TOKEN: dckr_pat_h4J2zfsoXd6x4N03BPadqzbbJVM #${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image back & front
        run: |
          docker build -t matope1/hipotecassist-backend:ci -f backend/Dockerfile backend/
          docker build -t matope1/hipotecassist-frontend:ci -f frontend/Dockerfile frontend/

      - name: Start with Docker Compose up
        run: |
          docker compose -f docker-compose.ci.yml up -d
          # Esperar a que el backend est√© listo
          until curl -s http://localhost:8000/; do
            echo "Esperando backend..."
            sleep 2
          done

      - name: Tests API endpoints
        run: |
          curl -s -f http://localhost:8000/

          curl -s -X POST http://localhost:8000/analisis \
            -H "Content-Type: application/json" \
            -d '{"tipo":"variable","capital_pendiente":100000,"anos_restantes":20,"euribor":3.5,"diferencial":1.0}' \
            -f

          curl -s -X POST http://localhost:8000/preguntar \
            -H "Content-Type: application/json" \
            -d '{"pregunta":"Hola"}' \
            -f

      - name: Clear with Compose down
        run: docker compose -f docker-compose.ci.yml down

      - name: Log in DockerHub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Push images to DockerHub
        if: success()
        run: |
          docker tag matope1/hipotecassist-backend:ci matope1/hipotecassist-backend:latest
          docker push matope1/hipotecassist-backend:latest
          docker tag matope1/hipotecassist-frontend:ci matope1/hipotecassist-frontend:latest
          docker push matope1/hipotecassist-frontend:latest


      # - name: Push frontend to DockerHub
      #   if: success()
      #   run: docker push matope1/hipotecassist-frontend:latest
