name: dockerflow

on:
  push:
    branches: [feature/dockerizar]
  workflow_dispatch:

jobs:
  buid-push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image to DockerHub
        run: |
          docker build -t matope1/hipotecassist-backend:latest -f backend/Dockerfile .
          docker build -t matope1/hipotecassist-frontend:latest -f frontend/Dockerfile .

      - name: Start with Docker Compose up
        run: |
          docker compose up -d
          sleep 15

      - name: Tests API endpoints
        run: |
          # GET
          curl -s -f http://localhost:8000/

          # POST /analisis
          curl -s -X POST http://localhost:8000/analisis \
            -H "Content-Type: application/json" \
            -d '{"tipo":"variable","capital_pendiente":100000,"anos_restantes":20,"euribor":3.5,"diferencial":1.0}' \
            -f

          # POST /preguntar
          curl -s -X POST http://localhost:8000/preguntar \
            -H "Content-Type: application/json" \
            -d '{"pregunta":"Hola"}' \
            -f

      - name: Clear with Compose down
        run: docker compose down

      - name: Log in DockerHub
        if: success()
        uses: docker/login-action@v2
        with:
          username: matope1
          password: JupiterPontia2025

      - name: Push backend to DockerHub
        if: success()
        run: docker push matope1/hipotecassist-backend:latest


      - name: Push frontend to DockerHub
        if: success()
        run: docker push matope1/hipotecassist-frontend:latest
